debug workflow

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -10,7 +10,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       kafka_changed: \${{ steps.file-changed.outputs.kafka_changed }}
-      storage_changed: \${{ steps.file-changed.outputs.storage_changed }}
+#      storage_changed: \${{ steps.file-changed.outputs.storage_changed }}
     steps:
       - name: Install sshpass
         run: sudo apt-get install -y sshpass
@@ -51,44 +51,44 @@ jobs:
           docker compose -f docker-compose.kafka.yaml up -d
           EOF
 
-  deploy-storage:
-    runs-on: ubuntu-latest
-    needs: setup
-    if: \${{ needs.setup.outputs.storage_changed == 'true' }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Debug outputs
-        run: |
-          echo "Kafka Changed: ${{ steps.file-changed.outputs.kafka_changed }}"
-          echo "Storage Changed: ${{ steps.file-changed.outputs.storage_changed }}"
-
-      - name: Update storage Compose
-        run: |
-          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./docker-config/docker-compose.storage.yaml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/eews-v2
-
-      - name: Run Docker Compose on remote server
-        run: |
-          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
-          cd eews-v2
-          docker compose -f docker-compose.storage.yaml up -d
-          EOF
-
-      - name: Run Migrations
-        run: |
-          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./configs/migrations.sql ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/eews-v2/configs/migrations.sql
-          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
-          cd eews-v2/configs
-          SQL_QUERY=$(<"migrations.sql")
-          if [[ -z "$SQL_QUERY" ]]; then
-              echo "Error: Unable to read the SQL file or the file is empty."
-              exit 1
-          fi
-          docker exec -i "new-eews-postgres" sh -c "PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -U ${{ secrets.DB_USER }} -d postgres" <<< "$SQL_QUERY"
-          if [[ $? -eq 0 ]]; then
-              echo "SQL query executed successfully inside the Docker container."
-          else
-              echo "Error: Failed to execute the SQL query inside the Docker container."
-          fi
-          EOF
+#  deploy-storage:
+#    runs-on: ubuntu-latest
+#    needs: setup
+#    if: \${{ needs.setup.outputs.storage_changed == 'true' }}
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v3
+#
+#      - name: Debug outputs
+#        run: |
+#          echo "Kafka Changed: ${{ steps.file-changed.outputs.kafka_changed }}"
+#          echo "Storage Changed: ${{ steps.file-changed.outputs.storage_changed }}"
+#
+#      - name: Update storage Compose
+#        run: |
+#          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./docker-config/docker-compose.storage.yaml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/eews-v2
+#
+#      - name: Run Docker Compose on remote server
+#        run: |
+#          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
+#          cd eews-v2
+#          docker compose -f docker-compose.storage.yaml up -d
+#          EOF
+#
+#      - name: Run Migrations
+#        run: |
+#          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./configs/migrations.sql ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/eews-v2/configs/migrations.sql
+#          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
+#          cd eews-v2/configs
+#          SQL_QUERY=$(<"migrations.sql")
+#          if [[ -z "$SQL_QUERY" ]]; then
+#              echo "Error: Unable to read the SQL file or the file is empty."
+#              exit 1
+#          fi
+#          docker exec -i "new-eews-postgres" sh -c "PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -U ${{ secrets.DB_USER }} -d postgres" <<< "$SQL_QUERY"
+#          if [[ $? -eq 0 ]]; then
+#              echo "SQL query executed successfully inside the Docker container."
+#          else
+#              echo "Error: Failed to execute the SQL query inside the Docker container."
+#          fi
+#          EOF
