attempt to fix workflow

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -9,8 +9,8 @@ jobs:
   setup:
     runs-on: ubuntu-latest
     outputs:
-      kafka_changed: ${{ steps.file-changed.outputs.kafka_changed }}
-      storage_changed: ${{ steps.file-changed.outputs.storage_changed }}
+      kafka_changed: \${{ steps.file-changed.outputs.kafka_changed }}
+      storage_changed: \${{ steps.file-changed.outputs.storage_changed }}
     steps:
       - name: Install sshpass
         run: sudo apt-get install -y sshpass
@@ -22,42 +22,31 @@ jobs:
         id: file-changed
         run: |
           git fetch origin main --depth=1
-          if git diff --quiet origin/main -- docker-config/docker-compose.kafka.yaml; then
-            echo "kafka_changed=false" >> $GITHUB_ENV
-          else
-            echo "kafka_changed=true" >> $GITHUB_ENV
-          fi
-
-          if git diff --quiet origin/main -- docker-config/docker-compose.storage.yaml configs/migrations.sql; then
-            echo "storage_changed=false" >> $GITHUB_ENV
-          else
-            echo "storage_changed=true" >> $GITHUB_ENV
-        env:
-          GITHUB_ENV: $GITHUB_ENV
+          echo "kafka_changed=\$(git diff --quiet origin/main -- docker-config/docker-compose.kafka.yaml || echo 'true')" >> \$GITHUB_OUTPUT
+          echo "storage_changed=\$(git diff --quiet origin/main -- docker-config/docker-compose.storage.yaml configs/migrations.sql || echo 'true')" >> \$GITHUB_OUTPUT
 
       - name: Create .env file
         run: |
-          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
+          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
           cd eews-v2
-          echo "POSTGRES_USER=${{ secrets.DB_USER }}" > .env
+          echo "POSTGRES_USER=${{ secrets.DB_USER }}" >> .env
           echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
-          EOF
 
   deploy-kafka:
     runs-on: ubuntu-latest
     needs: setup
-    if: ${{ env.kafka_changed == 'true' }}
+    if: \${{ needs.setup.outputs.kafka_changed == 'true' }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
 
       - name: Update Kafka Compose
         run: |
-          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ./docker-config/docker-compose.kafka.yaml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/eews-v2
+          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./docker-config/docker-compose.kafka.yaml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/eews-v2
 
       - name: Run Docker Compose on remote server
         run: |
-          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
+          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
           cd eews-v2
           docker compose -f docker-compose.kafka.yaml up -d
           EOF
@@ -65,34 +54,41 @@ jobs:
   deploy-storage:
     runs-on: ubuntu-latest
     needs: setup
-    if: ${{ env.storage_changed == 'true' }}
+    if: \${{ needs.setup.outputs.storage_changed == 'true' }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Update Storage Compose
+      - name: Debug outputs
         run: |
-          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ./docker-config/docker-compose.storage.yaml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/eews-v2
+          echo "Kafka Changed: ${{ steps.file-changed.outputs.kafka_changed }}"
+          echo "Storage Changed: ${{ steps.file-changed.outputs.storage_changed }}"
+
+      - name: Update storage Compose
+        run: |
+          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./docker-config/docker-compose.storage.yaml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/eews-v2
 
       - name: Run Docker Compose on remote server
         run: |
-          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
+          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
           cd eews-v2
           docker compose -f docker-compose.storage.yaml up -d
           EOF
 
       - name: Run Migrations
         run: |
-          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ./configs/migrations.sql ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/eews-v2/configs/migrations.sql
-          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
-          set -e
+          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./configs/migrations.sql ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/eews-v2/configs/migrations.sql
+          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
           cd eews-v2/configs
-          SQL_QUERY=$(cat migrations.sql)
+          SQL_QUERY=$(<"migrations.sql")
+          if [[ -z "$SQL_QUERY" ]]; then
+              echo "Error: Unable to read the SQL file or the file is empty."
+              exit 1
+          fi
           docker exec -i "new-eews-postgres" sh -c "PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -U ${{ secrets.DB_USER }} -d postgres" <<< "$SQL_QUERY"
           if [[ $? -eq 0 ]]; then
               echo "SQL query executed successfully inside the Docker container."
           else
               echo "Error: Failed to execute the SQL query inside the Docker container."
-              exit 1
           fi
           EOF
